server:
  port: 8003

spring:
  application:
    name: cloud-payment-service

eureka:
  instance:
    instance-id: payment8003
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka